"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { PlayCircle,Video } from "lucide-react";
type V={file_url:string;title:string|null;description:string|null;poster_url?:string|null};
const fallback:V[]=[
 {file_url:"/VID-20260618-WA0033.mp4",title:"MNB College Video 1",description:"School life and activities."},
 {file_url:"/VID-20260618-WA0034.mp4",title:"MNB College Video 2",description:"Learning and student development."},
 {file_url:"/VID-20260618-WA0035.mp4",title:"MNB College Video 3",description:"Events and school highlights."},
 {file_url:"/VID-20260618-WA0036.mp4",title:"MNB College Video 4",description:"MNB College community."},
];
export default function Page(){const [videos,setVideos]=useState<V[]>(fallback);const [current,setCurrent]=useState(0);useEffect(()=>{fetch('/api/media?section=videos').then(r=>r.ok?r.json():[]).then(d=>{if(Array.isArray(d)&&d.length)setVideos(d)}).catch(()=>{})},[]);const active=videos[current]||videos[0];return <main><section className="bg-[var(--mnb-navy)] text-white py-20"><div className="mx-auto max-w-7xl px-4"><p className="text-[var(--mnb-gold)] uppercase tracking-[.2em] font-bold">MNB College</p><h1 className="text-4xl md:text-5xl font-black mt-3">Videos</h1><p className="mt-4 text-blue-100 text-lg">Watch school events, student activities, worship and learning highlights.</p></div></section><section className="py-14 bg-[var(--mnb-light)]"><div className="mx-auto max-w-7xl px-4"><div className="grid lg:grid-cols-[2fr_1fr] gap-7"><div className="bg-white rounded-3xl overflow-hidden shadow-lg"><video key={active?.file_url} src={active?.file_url} controls poster={active?.poster_url||undefined} className="w-full aspect-video bg-black"/><div className="p-6"><h3 className="text-2xl font-black text-[var(--mnb-navy)]">{active?.title}</h3><p className="mt-3 text-gray-600">{active?.description}</p></div></div><div className="bg-white rounded-3xl p-5 shadow-lg h-fit"><h3 className="font-black text-xl text-[var(--mnb-navy)] mb-4 flex items-center gap-2"><Video className="text-[var(--mnb-gold)]"/>Video Playlist</h3><div className="max-h-[500px] overflow-y-auto grid gap-3">{videos.map((v,i)=><button key={`${v.file_url}-${i}`} onClick={()=>setCurrent(i)} className={`text-left rounded-2xl p-4 border ${i===current?'bg-[var(--mnb-navy)] text-white':'bg-[var(--mnb-light)]'}`}><div className="flex gap-3"><PlayCircle className={i===current?'text-[var(--mnb-gold)]':'text-[var(--mnb-purple)]'}/><div><h4 className="font-bold">{v.title}</h4><p className={`text-sm mt-1 ${i===current?'text-blue-100':'text-gray-600'}`}>{v.description}</p></div></div></button>)}</div></div></div><Link href="/gallery" className="mt-8 inline-block rounded-xl bg-[var(--mnb-navy)] text-white px-6 py-3 font-bold">Back to Gallery</Link></div></section></main>}
