import Image from "next/image";
import Link from "next/link";
import { sql } from "@/lib/db";

export const dynamic = "force-dynamic";
const fallback=[
 {file_url:"/image1.png",title:"School Assembly",description:"MNB College life and learning."},
 {file_url:"/image2.png",title:"Student Event",description:"MNB College life and learning."},
 {file_url:"/image3.png",title:"Student Life",description:"MNB College life and learning."},
 {file_url:"/IMG_20230630_151418.jpg",title:"Science Laboratory",description:"MNB College life and learning."},
 {file_url:"/IMG_20230630_171411.jpg",title:"Practical Learning",description:"MNB College life and learning."},
];
export default async function Page(){let images:any[]=fallback;try{const rows=await sql`SELECT file_url,title,description FROM website_media WHERE section='gallery' AND is_active=TRUE ORDER BY display_order,id`;if(rows.length)images=rows as any[]}catch{}
return <main><section className="bg-[var(--mnb-navy)] text-white py-20"><div className="mx-auto max-w-7xl px-4"><p className="text-[var(--mnb-gold)] uppercase tracking-[.2em] font-bold">MNB College</p><h1 className="text-4xl md:text-5xl font-black mt-3">Gallery</h1><p className="mt-4 max-w-2xl text-blue-100 text-lg">View moments of learning, worship, discipline, student life and practical education at MNB College.</p></div></section><section className="py-10 bg-[var(--mnb-light)]"><div className="mx-auto max-w-7xl px-4"><div className="flex items-center justify-between mb-6"><div><p className="text-[var(--mnb-gold)] uppercase tracking-[.2em] font-bold">Photo Highlights</p><h2 className="section-title text-3xl mt-2">Scroll Through MNB Moments</h2></div><Link href="/gallery/photos" className="hidden md:inline-block bg-[var(--mnb-navy)] text-white px-5 py-3 rounded-xl font-bold">View All Photos</Link></div><div className="overflow-x-auto pb-5"><div className="flex gap-5 min-w-max">{images.map((item,index)=><div key={`${item.file_url}-${index}`} className="relative h-80 w-[340px] md:w-[420px] flex-shrink-0 overflow-hidden rounded-3xl shadow-lg group"><Image src={item.file_url} alt={item.title||'Gallery image'} fill className="object-cover transition-transform duration-500 group-hover:scale-110" unoptimized={item.file_url.startsWith('http')}/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/20 to-transparent"/><div className="absolute bottom-0 p-6 text-white"><h3 className="text-2xl font-black">{item.title||'MNB College'}</h3><p className="mt-2 text-sm text-gray-200">{item.description||'MNB College life and learning.'}</p></div></div>)}</div></div></div></section><section className="py-16"><div className="mx-auto max-w-7xl px-4 grid lg:grid-cols-3 gap-10"><div className="lg:col-span-2"><h2 className="section-title text-3xl">Gallery</h2><p className="mt-4 text-gray-600 text-lg leading-8">Photo and video highlights from MNB College, including student assemblies, Christian life, science laboratories, academic activities, events and school facilities.</p></div><aside className="bg-[var(--mnb-light)] rounded-3xl p-7 h-fit"><h3 className="font-black text-xl text-[var(--mnb-navy)]">Quick Links</h3><div className="grid gap-3 mt-5"><Link href="/admissions/apply-online" className="bg-white p-4 rounded-xl">Apply Online</Link><Link href="/downloads/prospectus" className="bg-white p-4 rounded-xl">Prospectus</Link><Link href="/contact" className="bg-white p-4 rounded-xl">Contact Us</Link></div></aside></div></section></main>}
